### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by sirkrypt0** [All-Your-Locks-Are-Belong-To-Us/libmicrofido2#35]
- [x] Check that subfolders contain README if necessary
- [ ] Check main README (Examples have their own project structure and READMEs...)
- [ ] Unify compiling instructions in a single file, currently the AVR instructions are in the main README, the other architectures in the examples folder
- [x] Maybe README in examples dir
- [x] NRF Readme should be better structured
- [ ] ~~Possibly Atmega examples~~

**Comment by felix-gohla** [comment]
Related to #38.
